version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      
"9000:9000" # Puerto para la API de MinIO
"9001:9001" # Puerto para la consola de administración
environment:
  MINIO_ROOT_USER: minio # Cambia esto por tu usuario deseado
  MINIO_ROOT_PASSWORD: minio1234 # Cambia esto por tu contraseña deseada
command: server /data --console-address ":9001"
volumes:
minio-data:/data

volumes:
  minio-data: